'use strict';
const $=id=>document.getElementById(id);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n}
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':''}
async function api(path,method='GET',body){const options={method,credentials:'same-origin',cache:'no-store',redirect:'error',headers:{'X-Titanus-Command-Center':'1'}};if(body!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body)}const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw new Error(data.error||`API unavailable (${r.status})`);return data}
function badge(value){return el('span',value,['READY','ACTIVE','SUCCEEDED','RUNNING'].includes(value)?'badge':'badge warn')}
function row(target,values){const tr=el('tr');for(const value of values){const td=el('td');td.append(value instanceof Node?value:el('span',value));tr.append(td)}$(target).append(tr)}
function action(text,fn,secondary=false){const b=el('button',text,secondary?'secondary':'');b.type='button';b.addEventListener('click',async()=>{b.disabled=true;try{await fn();await refresh();notice('Action accepted by the API.')}catch(e){notice(e.message,true)}finally{b.disabled=false}});return b}
function empty(target,text){$(target).replaceChildren(el('p',text,'empty'))}
let refreshing=false;
async function refresh(){if(refreshing)return;refreshing=true;try{const [state,tasks,secrets,autoscalers,events]=await Promise.all([api('/v1/realm/state'),api('/v1/realm/tasks'),api('/v1/realm/secrets'),api('/v1/realm/autoscalers'),api('/v1/events')]);$('revision').textContent=state.revision;$('nodes-count').textContent=Object.values(state.nodes).filter(n=>n.state==='READY').length;$('units-count').textContent=Object.values(state.assignments).filter(a=>a.state==='ACTIVE').length;$('tasks-count').textContent=tasks.filter(t=>t.phase==='RUNNING').length;
 for(const id of ['nodes','fleet-list','task-list','secret-list','event-list'])$(id).replaceChildren();
 for(const n of Object.values(state.nodes).sort((a,b)=>a.id.localeCompare(b.id)))row('nodes',[n.id,badge(n.state),`${(n.resources.memory_used_bytes/1073741824).toFixed(2)} / ${(n.resources.memory_bytes/1073741824).toFixed(2)} GiB`,new Date(n.last_pulse).toLocaleString()]);
 for(const f of Object.values(state.fleets).sort((a,b)=>a.name.localeCompare(b.name))){const c=el('article',undefined,'card');c.append(el('h3',f.name));const assignments=Object.values(state.assignments).filter(a=>a.fleet===f.name);const a=autoscalers.find(a=>a.fleet===f.name);c.append(el('p',`${assignments.filter(a=>a.state==='ACTIVE').length} active / ${f.instances} desired · generation ${f.generation}`));c.append(el('p',a?`Autoscale ${a.min}–${a.max} · CPU target ${a.target_cpu}%`:'Manual scaling'));const controls=el('div',undefined,'actions');const input=el('input');input.type='number';input.min='0';input.max='1000';input.value=f.instances;input.setAttribute('aria-label',`Desired instances for ${f.name}`);controls.append(input,action('Scale',()=>api(`/v1/realm/fleets/${encodeURIComponent(f.name)}/scale`,'POST',{instances:Number(input.value)})));if(f.history?.length)controls.append(action('Rollback',()=>api(`/v1/realm/fleets/${encodeURIComponent(f.name)}/rollback`,'POST',{}),true));if(a)controls.append(action('Disable autoscale',()=>api(`/v1/realm/autoscalers/${encodeURIComponent(f.name)}`,'DELETE'),true));c.append(controls);$('fleet-list').append(c)}
 if(!Object.keys(state.fleets).length)empty('fleet-list','No Fleets in this Realm. Create a Fleet with the CLI or API.');
 for(const t of tasks.sort((a,b)=>a.name.localeCompare(b.name))){const c=el('article',undefined,'card');c.append(el('h3',t.name),badge(t.phase),el('p',`${t.node_id||'Awaiting placement'} · exit ${t.exit_code??'unconfirmed'}`));if(!['SUCCEEDED','FAILED','CANCELLED'].includes(t.phase))c.append(action(t.cancel_requested?'Cancellation pending':'Request cancellation',()=>api(`/v1/realm/tasks/${encodeURIComponent(t.name)}/cancel`,'POST',{}),true));$('task-list').append(c)}if(!tasks.length)empty('task-list','No Tasks submitted.');
 for(const s of secrets.sort((a,b)=>a.name.localeCompare(b.name)||a.version-b.version))row('secret-list',[s.name,s.version,s.key_id]);
 for(const e of events.slice(-40).reverse())row('event-list',[new Date(e.time).toLocaleTimeString(),e.operation||e.kind,e.actor||'runtime',e.status||e.kind]);notice(`Connected to ${state.name} · refreshed ${new Date().toLocaleTimeString()}`)
 }catch(e){for(const id of ['revision','nodes-count','units-count','tasks-count'])$(id).textContent='—';notice(`${e.message}. Displayed records may be stale; refresh after restoring API access.`,true)}finally{refreshing=false}}
function form(id,fn){$(id).addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await fn();await refresh();notice('Saved through the authenticated API.')}catch(err){notice(err.message,true)}finally{b.disabled=false}})}
form('autoscale-form',()=>{const values=Object.fromEntries(new FormData($('autoscale-form')));for(const k of Object.keys(values))if(k!=='fleet')values[k]=Number(values[k]);return api('/v1/realm/autoscalers','POST',values)});
form('task-form',()=>api('/v1/realm/tasks','POST',JSON.parse($('task-json').value)));
form('secret-form',async()=>{const bytes=new TextEncoder().encode($('secret-value').value);let raw='';for(const b of bytes)raw+=String.fromCharCode(b);try{await api(`/v1/realm/secrets/${encodeURIComponent($('secret-name').value)}`,'PUT',{value:btoa(raw)})}finally{bytes.fill(0);$('secret-value').value=''}});
$('refresh').addEventListener('click',refresh);for(const a of document.querySelectorAll('nav a'))a.addEventListener('click',()=>{for(const n of document.querySelectorAll('nav a'))n.classList.remove('active');a.classList.add('active')});refresh();setInterval(()=>{if(!document.hidden)refresh()},15000);
